server: 
    port: 8887
    context-path: /mbook
#thymeleaf的相关配置
spring: 
   thymeleaf: 
      #热部署文件，页面不产生缓存，及时更新
      cache: false
      content-type: text/html
      mode: LEGACYHTML5
 
       
      
